### ISSUE TITLE
An error occurred while training the model“ModuleNotFoundError: No module named 'models.CLNet'”

### ISSUE THREAD

**Issue by Kingxudong** [M3DV/RibSeg#13]
Traceback (most recent call last):
  File "e:/code/RibSeg/train_ribseg.py", line 204, in <module>
    main(args)
  File "e:/code/RibSeg/train_ribseg.py", line 71, in main
    MODEL = importlib.import_module('models.'+args.model)
  File "D:\Anaconda\envs\pytorch\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.CLNet'

**Comment by BelieferQAQ** [comment]
> 

hello ， my qq is 318831418.  we can communicate

**Comment by nubee97** [comment]
I'm experiencing the same issue can you please assist me in solving this?

**Comment by ShixuanGu** [comment]
it's the relative path issue, u could change it to absolute path
